.\" Copyright (c) 2016, Niko Kiiskinen
.\"
.\" %%%LICENSE_START(GPLv2+_DOC_FULL)
.\" This is free documentation; you can redistribute it and/or
.\" modify it under the terms of the GNU General Public License as
.\" published by the Free Software Foundation; either version 2 of
.\" the License, or (at your option) any later version.
.\"
.\" The GNU General Public License's references to "object code"
.\" and "executables" are to be interpreted as the output of any
.\" document formatting or typesetting system, including
.\" intermediate and printed output.
.\"
.\" This manual is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\"
.\" You should have received a copy of the GNU General Public
.\" License along with this manual; if not, see
.\" <http://www.gnu.org/licenses/>.
.\" %%%LICENSE_END
.\"
.\"     @(#)fsck.lolfs.3 0.30 2016/12/17
.\"
.\" Modified, niko, 2016-12-17
.\"
.de URL
\\$2 \(laURL: \\$1 \(ra\\$3
..
.if \n[.g] .mso www.tmac
.TH "fsck.lolfs" "3" "16 December 2016" "LOLFS v0.30" "Lolfs Package Manual"
.SH "NAME"
fsck.lolfs \- check lolfs container for errors
.SH "SYNOPSIS"
.SY fsck.lolfs
.OP \-hvd
.RI [ file
.IR .\|.\|. ]
.YS
.SH "DESCRIPTION"
.B fsck.lolfs
is used to check and optionally repair one or more
.B lolfs
containers. Usually containers are normal files but in Linux,
a container may also be a device name (e.g. /dev/hdc1).
The
.B fsck.lolfs
command is followed by the name of the
.B lolfs
container \fIfile\fP or the \fIdevice\fP.
.SH "OPTIONS"
.TP
.B \-v \-\-version
Shows fsck.lolfs program version.
.TP
.B \-h \-\-help
Shows a short description of usage.
.TP
.B \-d \-\-details
Show more information about the container.
.SH "EXAMPLES"
.TP
fsck.lolfs my.db
.IP
Checks the lolfs container 'my.db' for errors.
.TP
fsck.lolfs -d my.db
.IP
Checks the container 'my.db' for errors and output
detailed information.
.SH "ENVIRONMENT"
Not implemented.
.SH "DIAGNOSTICS"
The
.B fsck.lolfs
program returns 0 after succesful execution.
Otherwise the return value is < 0.
.SH "AUTHOR"
Written by
.MT lolfs.bugs@\:gmail.com
Niko Kiiskinen.
.ME
.SH "SEE ALSO"
.BR mkfs.lolfs(3),
.BR lol(3).
.PP
The full documentation for
.B lolfs
related commands and
.B
C API
is maintained as man manual pages. If the
.B lolfs
package is properly installed at your site.
.SH "COPYRIGHT"
Copyright \(co 2015, 2016 Niko Kiiskinen.
.BR
.PP
License GNU GPL version 2 or later.
.URL https://\:www.gnu.org/\:licenses
.BR
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
.SH "COLOPHON"
This page is part of release 0.30 of the lolfs project
man-pages. The website of the project and the latest version,
can be found at Github:
.URL https://\:nkiiskin.github.io/\:lolfs
